<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[开始准备测试数据 ]]>
    </line>
    <line>
      <![CDATA[资料收取 15_14]]>
    </line>
    <line>
      <![CDATA[<br/><img src="D:\work_space\js_de\debug\SeleniumConfig\bin\Debug\SootScreens\2019-03-20\15_14\资料收取 15_14.png"  hight="900" width="900" />]]>
    </line>
  </reporter-output>
  <suite name="测试所有登记流程-房地登记-首次登记" duration-ms="114" started-at="2019-03-20T07:15:15Z" finished-at="2019-03-20T07:15:16Z">
    <groups>
    </groups>
    <test name="断言详情查看" duration-ms="114" started-at="2019-03-20T07:15:15Z" finished-at="2019-03-20T07:15:16Z">
      <class name="Test.DataProviderSet_Assert">
        <test-method status="PASS" signature="insetToExcel()[pri:0, instance:Test.DataProviderSet_Assert@2f40a43]" name="insetToExcel" is-config="true" duration-ms="693" started-at="2019-03-20T15:15:15Z" finished-at="2019-03-20T15:15:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insetToExcel -->
        <test-method status="FAIL" signature="star(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Test.DataProviderSet_Assert@2f40a43]" name="star" duration-ms="0" started-at="2019-03-20T15:15:16Z" data-provider="AssertData" finished-at="2019-03-20T15:15:16Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at configSelenium.ConfigSeleniumStart.dotestng(ConfigSeleniumStart.java:1067)
	at configSelenium.ConfigSeleniumStart.main(ConfigSeleniumStart.java:188)
Caused by: java.lang.NegativeArraySizeException
	at Test.DataProviderSet_Assert.getData(DataProviderSet_Assert.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- star -->
        <test-method status="PASS" signature="deleteExcel()[pri:0, instance:Test.DataProviderSet_Assert@2f40a43]" name="deleteExcel" is-config="true" duration-ms="9" started-at="2019-03-20T15:15:16Z" finished-at="2019-03-20T15:15:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteExcel -->
      </class> <!-- Test.DataProviderSet_Assert -->
    </test> <!-- 断言详情查看 -->
  </suite> <!-- 测试所有登记流程-房地登记-首次登记 -->
</testng-results>
